// <auto-generated />
using EveLoader.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EveLoader.Repositories.Migrations
{
    [DbContext(typeof(EveDbContext))]
    [Migration("20260928152639_Migration_20260928_162636")]
    partial class Migration_20260928_162636
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EveLoaderEntities.AgentType", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AgentTypes");
                });

            modelBuilder.Entity("EveLoaderEntities.AgentsInSpace", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("DungeonID")
                        .HasColumnType("bigint");

                    b.Property<long>("SolarSystemID")
                        .HasColumnType("bigint");

                    b.Property<long>("SpawnPointID")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("AgentsInSpace");
                });

            modelBuilder.Entity("EveLoaderEntities.Ancestry", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("BloodlineID")
                        .HasColumnType("bigint");

                    b.Property<long>("Charisma")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IconID")
                        .HasColumnType("bigint");

                    b.Property<long>("Intelligence")
                        .HasColumnType("bigint");

                    b.Property<long>("Memory")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Perception")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Willpower")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("Ancestries");
                });

            modelBuilder.Entity("EveLoaderEntities.Archetype", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Archetypes");
                });

            modelBuilder.Entity("EveLoaderEntities.Bloodline", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("Charisma")
                        .HasColumnType("bigint");

                    b.Property<long>("CorporationID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IconID")
                        .HasColumnType("bigint");

                    b.Property<long>("Intelligence")
                        .HasColumnType("bigint");

                    b.Property<long>("Memory")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Perception")
                        .HasColumnType("bigint");

                    b.Property<long>("RaceID")
                        .HasColumnType("bigint");

                    b.Property<long>("Willpower")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("Bloodlines");
                });

            modelBuilder.Entity("EveLoaderEntities.Blueprint", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("BlueprintTypeID")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxProductionLimit")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("Blueprints");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintActivities", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long>("BlueprintId")
                        .HasColumnType("bigint");

                    b.Property<long>("CopyingTime")
                        .HasColumnType("bigint");

                    b.Property<long?>("InventionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ManufacturingId")
                        .HasColumnType("bigint");

                    b.Property<long>("ResearchMaterialTime")
                        .HasColumnType("bigint");

                    b.Property<long>("ResearchTimeTime")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("BlueprintId")
                        .IsUnique();

                    b.HasIndex("InventionId")
                        .IsUnique()
                        .HasFilter("[InventionId] IS NOT NULL");

                    b.HasIndex("ManufacturingId")
                        .IsUnique()
                        .HasFilter("[ManufacturingId] IS NOT NULL");

                    b.ToTable("BlueprintActivities");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInvention", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("BlueprintInvention");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInventionMaterial", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("BlueprintInventionId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("BlueprintInventionId");

                    b.ToTable("BlueprintInventionMaterial");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInventionProduct", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("BlueprintInventionId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Probability")
                        .HasColumnType("float");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("BlueprintInventionId");

                    b.ToTable("BlueprintInventionProduct");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInventionSkill", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("BlueprintInventionId")
                        .HasColumnType("bigint");

                    b.Property<long>("Level")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("BlueprintInventionId");

                    b.ToTable("BlueprintInventionSkill");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturing", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("BlueprintManufacturing");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturingMaterial", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("BlueprintManufacturingId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("BlueprintManufacturingId");

                    b.ToTable("BlueprintManufacturingMaterial");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturingProduct", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("BlueprintManufacturingId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("BlueprintManufacturingId");

                    b.ToTable("BlueprintManufacturingProduct");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturingSkill", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("BlueprintManufacturingId")
                        .HasColumnType("bigint");

                    b.Property<long>("Level")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("BlueprintManufacturingId");

                    b.ToTable("BlueprintManufacturingSkill");
                });

            modelBuilder.Entity("EveLoaderEntities.Category", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long?>("IconID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.HasKey("Key");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EveLoaderEntities.Certificate", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("GroupID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("EveLoaderEntities.CertificateRecommendedFor", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("CertificateKey")
                        .HasColumnType("bigint");

                    b.Property<long>("RecommendedFor")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("CertificateKey");

                    b.ToTable("CertificateRecommendedFor");
                });

            modelBuilder.Entity("EveLoaderEntities.CertificateSkillType", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long>("Advanced")
                        .HasColumnType("bigint");

                    b.Property<long>("Basic")
                        .HasColumnType("bigint");

                    b.Property<long?>("CertificateKey")
                        .HasColumnType("bigint");

                    b.Property<long>("Elite")
                        .HasColumnType("bigint");

                    b.Property<long>("Improved")
                        .HasColumnType("bigint");

                    b.Property<long>("Standard")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("CertificateKey");

                    b.ToTable("CertificateSkillType");
                });

            modelBuilder.Entity("EveLoaderEntities.CharacterAttribute", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IconID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("CharacterAttributes");
                });

            modelBuilder.Entity("EveLoaderEntities.CharacterTitle", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("CharacterTitles");
                });

            modelBuilder.Entity("EveLoaderEntities.CloneGrade", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("CloneGrades");
                });

            modelBuilder.Entity("EveLoaderEntities.CloneGradeSkill", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("CloneGradeKey")
                        .HasColumnType("bigint");

                    b.Property<long>("Level")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("CloneGradeKey");

                    b.ToTable("CloneGradeSkill");
                });

            modelBuilder.Entity("EveLoaderEntities.CompressibleType", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("CompressedTypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("CompressibleTypes");
                });

            modelBuilder.Entity("EveLoaderEntities.ContrabandFaction", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<double>("AttackMinSec")
                        .HasColumnType("float");

                    b.Property<double>("ConfiscateMinSec")
                        .HasColumnType("float");

                    b.Property<long?>("ContrabandTypeKey")
                        .HasColumnType("bigint");

                    b.Property<double>("FineByValue")
                        .HasColumnType("float");

                    b.Property<double>("StandingLoss")
                        .HasColumnType("float");

                    b.HasKey("Key");

                    b.HasIndex("ContrabandTypeKey");

                    b.ToTable("ContrabandFaction");
                });

            modelBuilder.Entity("EveLoaderEntities.ContrabandType", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("ContrabandTypes");
                });

            modelBuilder.Entity("EveLoaderEntities.ControlTowerResource", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("ControlTowerResources");
                });

            modelBuilder.Entity("EveLoaderEntities.ControlTowerResourceItem", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("ControlTowerResourceKey")
                        .HasColumnType("bigint");

                    b.Property<long?>("FactionID")
                        .HasColumnType("bigint");

                    b.Property<double?>("MinSecurityLevel")
                        .HasColumnType("float");

                    b.Property<long>("Purpose")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("ResourceTypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("ControlTowerResourceKey");

                    b.ToTable("ControlTowerResourceItem");
                });

            modelBuilder.Entity("EveLoaderEntities.CorporationActivity", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("CorporationActivities");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffCollection", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("AggregateMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeveloperDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShowOutputValueInUI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("DBuffCollections");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffItemModifier", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("DBuffCollectionId")
                        .HasColumnType("bigint");

                    b.Property<long>("DogmaAttributeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("DBuffCollectionId");

                    b.ToTable("DBuffItemModifier");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffLocationGroupModifier", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("DBuffCollectionId")
                        .HasColumnType("bigint");

                    b.Property<long>("DogmaAttributeID")
                        .HasColumnType("bigint");

                    b.Property<long>("GroupID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("DBuffCollectionId");

                    b.ToTable("DBuffLocationGroupModifier");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffLocationModifier", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("DBuffCollectionId")
                        .HasColumnType("bigint");

                    b.Property<long>("DogmaAttributeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("DBuffCollectionId");

                    b.ToTable("DBuffLocationModifier");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffLocationRequiredSkillModifier", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("DBuffCollectionId")
                        .HasColumnType("bigint");

                    b.Property<long>("DogmaAttributeID")
                        .HasColumnType("bigint");

                    b.Property<long>("SkillID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("DBuffCollectionId");

                    b.ToTable("DBuffLocationRequiredSkillModifier");
                });

            modelBuilder.Entity("EveLoaderEntities.DogmaAttribute", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("AttributeCategoryID")
                        .HasColumnType("bigint");

                    b.Property<long>("DataType")
                        .HasColumnType("bigint");

                    b.Property<double>("DefaultValue")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisplayWhenZero")
                        .HasColumnType("bit");

                    b.Property<bool>("HighIsGood")
                        .HasColumnType("bit");

                    b.Property<long?>("IconID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<bool>("Stackable")
                        .HasColumnType("bit");

                    b.Property<string>("TooltipDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TooltipTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UnitID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("DogmaAttributes");
                });

            modelBuilder.Entity("EveLoaderEntities.DogmaAttributeCategory", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("DogmaAttributeCategories");
                });

            modelBuilder.Entity("EveLoaderEntities.DogmaEffect", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisallowAutoRepeat")
                        .HasColumnType("bit");

                    b.Property<long?>("DischargeAttributeID")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Distribution")
                        .HasColumnType("bigint");

                    b.Property<long?>("DurationAttributeID")
                        .HasColumnType("bigint");

                    b.Property<long>("EffectCategoryID")
                        .HasColumnType("bigint");

                    b.Property<bool>("ElectronicChance")
                        .HasColumnType("bit");

                    b.Property<long?>("FalloffAttributeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Guid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IconID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAssistance")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOffensive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWarpSafe")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PropulsionChance")
                        .HasColumnType("bit");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<long?>("RangeAttributeID")
                        .HasColumnType("bigint");

                    b.Property<bool>("RangeChance")
                        .HasColumnType("bit");

                    b.Property<long?>("TrackingSpeedAttributeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("DogmaEffects");
                });

            modelBuilder.Entity("EveLoaderEntities.DogmaEffectModifierInfo", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("DogmaEffectKey")
                        .HasColumnType("bigint");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Func")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ModifiedAttributeID")
                        .HasColumnType("bigint");

                    b.Property<long>("ModifyingAttributeID")
                        .HasColumnType("bigint");

                    b.Property<long>("Operation")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("DogmaEffectKey");

                    b.ToTable("DogmaEffectModifierInfo");
                });

            modelBuilder.Entity("EveLoaderEntities.DogmaUnit", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("DogmaUnits");
                });

            modelBuilder.Entity("EveLoaderEntities.Dungeon", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string>("AllowedShipsList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ArchetypeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FactionID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Dungeons");
                });

            modelBuilder.Entity("EveLoaderEntities.DynamicItemAttribute", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("DynamicItemAttributes");
                });

            modelBuilder.Entity("EveLoaderEntities.DynamicItemAttributeRange", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("DynamicItemAttributeId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("HighIsGood")
                        .HasColumnType("bit");

                    b.Property<double>("Max")
                        .HasColumnType("float");

                    b.Property<double>("Min")
                        .HasColumnType("float");

                    b.HasKey("Key");

                    b.HasIndex("DynamicItemAttributeId");

                    b.ToTable("DynamicItemAttributeRange");
                });

            modelBuilder.Entity("EveLoaderEntities.DynamicItemInputOutputMapping", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.PrimitiveCollection<string>("ApplicableTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DynamicItemAttributeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ResultingType")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("DynamicItemAttributeId");

                    b.ToTable("DynamicItemInputOutputMapping");
                });

            modelBuilder.Entity("EveLoaderEntities.EpicArc", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("ArcRestartInterval")
                        .HasColumnType("bigint");

                    b.Property<long?>("FactionID")
                        .HasColumnType("bigint");

                    b.Property<long>("IconID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("EpicArcs");
                });

            modelBuilder.Entity("EveLoaderEntities.EpicArcMission", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long>("AgentID")
                        .HasColumnType("bigint");

                    b.Property<long?>("EpicArcKey")
                        .HasColumnType("bigint");

                    b.Property<long?>("FailMissionID")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string>("NextMissions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("EpicArcKey");

                    b.ToTable("EpicArcMission");
                });

            modelBuilder.Entity("EveLoaderEntities.Faction", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("CorporationID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlatLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlatLogoWithName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IconID")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string>("MemberRaces")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MilitiaCorporationID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SizeFactor")
                        .HasColumnType("float");

                    b.Property<long>("SolarSystemID")
                        .HasColumnType("bigint");

                    b.Property<bool>("UniqueName")
                        .HasColumnType("bit");

                    b.HasKey("Key");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchema", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("FreelanceJobSchemas");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchemaBooleanOption", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("FreelanceJobSchemaBooleanOption");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchemaBooleanParameter", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<string>("ChoiceLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Default")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OptionFalseKey")
                        .HasColumnType("bigint");

                    b.Property<long>("OptionTrueKey")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("OptionFalseKey")
                        .IsUnique();

                    b.HasIndex("OptionTrueKey")
                        .IsUnique();

                    b.ToTable("FreelanceJobSchemaBooleanParameter");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchemaContributionMultiplier", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<double>("DefaultValue")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxValue")
                        .HasColumnType("float");

                    b.Property<double>("MinValue")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnsetDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("FreelanceJobSchemaContributionMultiplier");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchemaEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.PrimitiveCollection<string>("ContentTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ContributionMultiplierKey")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FreelanceJobSchemaKey")
                        .HasColumnType("bigint");

                    b.Property<string>("IconID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MaxContributionsPerParticipantKey")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxProgressPerContributionKey")
                        .HasColumnType("bigint");

                    b.Property<string>("ProgressDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RewardDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("ContributionMultiplierKey")
                        .IsUnique();

                    b.HasIndex("FreelanceJobSchemaKey");

                    b.HasIndex("MaxContributionsPerParticipantKey")
                        .IsUnique();

                    b.HasIndex("MaxProgressPerContributionKey")
                        .IsUnique();

                    b.ToTable("FreelanceJobSchemaEntry");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchemaInventoryType", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.PrimitiveCollection<string>("AcceptedValueTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnsetDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("FreelanceJobSchemaInventoryType");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchemaItemDelivery", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long>("DeliveryLocationKey")
                        .HasColumnType("bigint");

                    b.Property<string>("IconID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MaxEntries")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnsetDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("DeliveryLocationKey")
                        .IsUnique();

                    b.ToTable("FreelanceJobSchemaItemDelivery");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchemaLimit", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnsetDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("FreelanceJobSchemaLimit");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchemaMatcher", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.PrimitiveCollection<string>("AcceptedValueTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MaxEntries")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Optional")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnsetDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("FreelanceJobSchemaMatcher");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchemaParameter", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("BooleanKey")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreelanceJobSchemaEntryKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IconID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("InventoryTypeKey")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemDeliveryKey")
                        .HasColumnType("bigint");

                    b.Property<long>("MatcherKey")
                        .HasColumnType("bigint");

                    b.Property<long?>("MaxEntries")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Optional")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnsetDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("BooleanKey")
                        .IsUnique();

                    b.HasIndex("FreelanceJobSchemaEntryKey");

                    b.HasIndex("InventoryTypeKey")
                        .IsUnique();

                    b.HasIndex("ItemDeliveryKey")
                        .IsUnique();

                    b.HasIndex("MatcherKey")
                        .IsUnique();

                    b.ToTable("FreelanceJobSchemaParameter");
                });

            modelBuilder.Entity("EveLoaderEntities.Graphic", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("GraphicFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconFolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SofFactionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SofHullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SofRaceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Graphics");
                });

            modelBuilder.Entity("EveLoaderEntities.GraphicMaterialSet", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<double>("ColorHullA")
                        .HasColumnType("float");

                    b.Property<double>("ColorHullB")
                        .HasColumnType("float");

                    b.Property<double>("ColorHullG")
                        .HasColumnType("float");

                    b.Property<double>("ColorHullR")
                        .HasColumnType("float");

                    b.Property<double>("ColorPrimaryA")
                        .HasColumnType("float");

                    b.Property<double>("ColorPrimaryB")
                        .HasColumnType("float");

                    b.Property<double>("ColorPrimaryG")
                        .HasColumnType("float");

                    b.Property<double>("ColorPrimaryR")
                        .HasColumnType("float");

                    b.Property<double>("ColorSecondaryA")
                        .HasColumnType("float");

                    b.Property<double>("ColorSecondaryB")
                        .HasColumnType("float");

                    b.Property<double>("ColorSecondaryG")
                        .HasColumnType("float");

                    b.Property<double>("ColorSecondaryR")
                        .HasColumnType("float");

                    b.Property<double>("ColorWindowA")
                        .HasColumnType("float");

                    b.Property<double>("ColorWindowB")
                        .HasColumnType("float");

                    b.Property<double>("ColorWindowG")
                        .HasColumnType("float");

                    b.Property<double>("ColorWindowR")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SofFactionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SofRaceHint")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("GraphicMaterialSets");
                });

            modelBuilder.Entity("EveLoaderEntities.Group", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<bool>("Anchorable")
                        .HasColumnType("bit");

                    b.Property<bool>("Anchored")
                        .HasColumnType("bit");

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint");

                    b.Property<bool>("FittableNonSingleton")
                        .HasColumnType("bit");

                    b.Property<long?>("IconID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<bool>("UseBasePrice")
                        .HasColumnType("bit");

                    b.HasKey("Key");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("EveLoaderEntities.Icon", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("IconFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Icons");
                });

            modelBuilder.Entity("EveLoaderEntities.Landmark", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IconID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Landmarks");
                });

            modelBuilder.Entity("EveLoaderEntities.MapAsteroidBelt", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("CelestialIndex")
                        .HasColumnType("bigint");

                    b.Property<double>("CelestialStatisticsDensity")
                        .HasColumnType("float");

                    b.Property<double>("CelestialStatisticsEccentricity")
                        .HasColumnType("float");

                    b.Property<double>("CelestialStatisticsEscapeVelocity")
                        .HasColumnType("float");

                    b.Property<bool>("CelestialStatisticsLocked")
                        .HasColumnType("bit");

                    b.Property<double>("CelestialStatisticsMassDust")
                        .HasColumnType("float");

                    b.Property<double>("CelestialStatisticsMassGas")
                        .HasColumnType("float");

                    b.Property<double>("CelestialStatisticsOrbitPeriod")
                        .HasColumnType("float");

                    b.Property<double>("CelestialStatisticsOrbitRadius")
                        .HasColumnType("float");

                    b.Property<double?>("CelestialStatisticsPressure")
                        .HasColumnType("float");

                    b.Property<double>("CelestialStatisticsRotationRate")
                        .HasColumnType("float");

                    b.Property<string>("CelestialStatisticsSpectralClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CelestialStatisticsSurfaceGravity")
                        .HasColumnType("float");

                    b.Property<double>("CelestialStatisticsTemperature")
                        .HasColumnType("float");

                    b.Property<long>("OrbitID")
                        .HasColumnType("bigint");

                    b.Property<long>("OrbitIndex")
                        .HasColumnType("bigint");

                    b.Property<double>("PositionX")
                        .HasColumnType("float");

                    b.Property<double>("PositionY")
                        .HasColumnType("float");

                    b.Property<double>("PositionZ")
                        .HasColumnType("float");

                    b.Property<double>("Radius")
                        .HasColumnType("float");

                    b.Property<long>("SolarSystemID")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("MapAsteroidBelts");
                });

            modelBuilder.Entity("EveLoaderEntities.MapConstellation", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long?>("FactionID")
                        .HasColumnType("bigint");

                    b.Property<double>("MapConstellationX")
                        .HasColumnType("float");

                    b.Property<double>("MapConstellationY")
                        .HasColumnType("float");

                    b.Property<double>("MapConstellationZ")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RegionID")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string>("SolarSystemIDs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("WormholeClassID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("MapConstellations");
                });

            modelBuilder.Entity("EveLoaderEntities.MapMoon", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("CelestialIndex")
                        .HasColumnType("bigint");

                    b.Property<double>("Density")
                        .HasColumnType("float");

                    b.Property<double>("Eccentricity")
                        .HasColumnType("float");

                    b.Property<double>("EscapeVelocity")
                        .HasColumnType("float");

                    b.Property<long>("HeightMap1")
                        .HasColumnType("bigint");

                    b.Property<long>("HeightMap2")
                        .HasColumnType("bigint");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit");

                    b.Property<double>("MassDust")
                        .HasColumnType("float");

                    b.Property<double>("MassGas")
                        .HasColumnType("float");

                    b.Property<long>("OrbitID")
                        .HasColumnType("bigint");

                    b.Property<double>("OrbitPeriod")
                        .HasColumnType("float");

                    b.Property<double>("OrbitRadius")
                        .HasColumnType("float");

                    b.Property<bool>("Population")
                        .HasColumnType("bit");

                    b.Property<double?>("Pressure")
                        .HasColumnType("float");

                    b.Property<double>("Radius")
                        .HasColumnType("float");

                    b.Property<double>("RotationRate")
                        .HasColumnType("float");

                    b.Property<long>("ShaderPreset")
                        .HasColumnType("bigint");

                    b.Property<long>("SolarSystemID")
                        .HasColumnType("bigint");

                    b.Property<string>("SpectralClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SurfaceGravity")
                        .HasColumnType("float");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.Property<double>("Z")
                        .HasColumnType("float");

                    b.HasKey("Key");

                    b.ToTable("MapMoons");
                });

            modelBuilder.Entity("EveLoaderEntities.MapPlanet", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string>("AsteroidBeltIDs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CelestialIndex")
                        .HasColumnType("bigint");

                    b.Property<double>("Density")
                        .HasColumnType("float");

                    b.Property<double>("Eccentricity")
                        .HasColumnType("float");

                    b.Property<double>("EscapeVelocity")
                        .HasColumnType("float");

                    b.Property<long>("HeightMap1")
                        .HasColumnType("bigint");

                    b.Property<long>("HeightMap2")
                        .HasColumnType("bigint");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit");

                    b.Property<double>("MassDust")
                        .HasColumnType("float");

                    b.Property<double>("MassGas")
                        .HasColumnType("float");

                    b.PrimitiveCollection<string>("MoonIDs")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("NpcStationIDs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrbitID")
                        .HasColumnType("bigint");

                    b.Property<double>("OrbitPeriod")
                        .HasColumnType("float");

                    b.Property<double>("OrbitRadius")
                        .HasColumnType("float");

                    b.Property<bool>("Population")
                        .HasColumnType("bit");

                    b.Property<double?>("Pressure")
                        .HasColumnType("float");

                    b.Property<double>("Radius")
                        .HasColumnType("float");

                    b.Property<double>("RotationRate")
                        .HasColumnType("float");

                    b.Property<long>("ShaderPreset")
                        .HasColumnType("bigint");

                    b.Property<long>("SolarSystemID")
                        .HasColumnType("bigint");

                    b.Property<string>("SpectralClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SurfaceGravity")
                        .HasColumnType("float");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.Property<double>("Z")
                        .HasColumnType("float");

                    b.HasKey("Key");

                    b.ToTable("MapPlanets");
                });

            modelBuilder.Entity("EveLoaderEntities.MapRegion", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string>("ConstellationIDs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FactionID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NebulaID")
                        .HasColumnType("bigint");

                    b.Property<long?>("WormholeClassID")
                        .HasColumnType("bigint");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.Property<double>("Z")
                        .HasColumnType("float");

                    b.HasKey("Key");

                    b.ToTable("MapRegions");
                });

            modelBuilder.Entity("EveLoaderEntities.MapSecondarySun", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("EffectBeaconTypeID")
                        .HasColumnType("bigint");

                    b.Property<long>("SolarSystemID")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.Property<double>("Z")
                        .HasColumnType("float");

                    b.HasKey("Key");

                    b.ToTable("MapSecondarySuns");
                });

            modelBuilder.Entity("EveLoaderEntities.MapSolarSystem", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Border")
                        .HasColumnType("bit");

                    b.Property<long>("ConstellationID")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Corridor")
                        .HasColumnType("bit");

                    b.Property<bool?>("Fringe")
                        .HasColumnType("bit");

                    b.Property<bool?>("Hub")
                        .HasColumnType("bit");

                    b.Property<bool?>("International")
                        .HasColumnType("bit");

                    b.Property<double>("Luminosity")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("PlanetIDs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Position2DX")
                        .HasColumnType("float");

                    b.Property<double?>("Position2DY")
                        .HasColumnType("float");

                    b.Property<double>("Radius")
                        .HasColumnType("float");

                    b.Property<long>("RegionID")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Regional")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SecurityStatus")
                        .HasColumnType("float");

                    b.Property<long>("StarID")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string>("StargateIDs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.Property<double>("Z")
                        .HasColumnType("float");

                    b.HasKey("Key");

                    b.ToTable("MapSolarSystems");
                });

            modelBuilder.Entity("EveLoaderEntities.MapStar", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<double>("Age")
                        .HasColumnType("float");

                    b.Property<double>("Life")
                        .HasColumnType("float");

                    b.Property<double>("Luminosity")
                        .HasColumnType("float");

                    b.Property<long>("Radius")
                        .HasColumnType("bigint");

                    b.Property<long>("SolarSystemID")
                        .HasColumnType("bigint");

                    b.Property<string>("SpectralClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("MapStars");
                });

            modelBuilder.Entity("EveLoaderEntities.MapStargate", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("SolarSystemID")
                        .HasColumnType("bigint");

                    b.Property<long>("StargateDestinationSolarSystemID")
                        .HasColumnType("bigint");

                    b.Property<long>("StargateDestinationStargateID")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.Property<double>("Z")
                        .HasColumnType("float");

                    b.HasKey("Key");

                    b.ToTable("MapStargates");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintActivities", b =>
                {
                    b.HasOne("EveLoaderEntities.Blueprint", null)
                        .WithOne("Activities")
                        .HasForeignKey("EveLoaderEntities.BlueprintActivities", "BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EveLoaderEntities.BlueprintInvention", "Invention")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.BlueprintActivities", "InventionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EveLoaderEntities.BlueprintManufacturing", "Manufacturing")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.BlueprintActivities", "ManufacturingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Invention");

                    b.Navigation("Manufacturing");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInventionMaterial", b =>
                {
                    b.HasOne("EveLoaderEntities.BlueprintInvention", null)
                        .WithMany("Materials")
                        .HasForeignKey("BlueprintInventionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInventionProduct", b =>
                {
                    b.HasOne("EveLoaderEntities.BlueprintInvention", null)
                        .WithMany("Products")
                        .HasForeignKey("BlueprintInventionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInventionSkill", b =>
                {
                    b.HasOne("EveLoaderEntities.BlueprintInvention", null)
                        .WithMany("Skills")
                        .HasForeignKey("BlueprintInventionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturingMaterial", b =>
                {
                    b.HasOne("EveLoaderEntities.BlueprintManufacturing", null)
                        .WithMany("Materials")
                        .HasForeignKey("BlueprintManufacturingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturingProduct", b =>
                {
                    b.HasOne("EveLoaderEntities.BlueprintManufacturing", null)
                        .WithMany("Products")
                        .HasForeignKey("BlueprintManufacturingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturingSkill", b =>
                {
                    b.HasOne("EveLoaderEntities.BlueprintManufacturing", null)
                        .WithMany("Skills")
                        .HasForeignKey("BlueprintManufacturingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.CertificateRecommendedFor", b =>
                {
                    b.HasOne("EveLoaderEntities.Certificate", null)
                        .WithMany("RecommendedFor")
                        .HasForeignKey("CertificateKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.CertificateSkillType", b =>
                {
                    b.HasOne("EveLoaderEntities.Certificate", null)
                        .WithMany("SkillTypes")
                        .HasForeignKey("CertificateKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.CloneGradeSkill", b =>
                {
                    b.HasOne("EveLoaderEntities.CloneGrade", null)
                        .WithMany("Skills")
                        .HasForeignKey("CloneGradeKey");
                });

            modelBuilder.Entity("EveLoaderEntities.ContrabandFaction", b =>
                {
                    b.HasOne("EveLoaderEntities.ContrabandType", null)
                        .WithMany("Factions")
                        .HasForeignKey("ContrabandTypeKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.ControlTowerResourceItem", b =>
                {
                    b.HasOne("EveLoaderEntities.ControlTowerResource", null)
                        .WithMany("Resources")
                        .HasForeignKey("ControlTowerResourceKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffItemModifier", b =>
                {
                    b.HasOne("EveLoaderEntities.DBuffCollection", null)
                        .WithMany("ItemModifiers")
                        .HasForeignKey("DBuffCollectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffLocationGroupModifier", b =>
                {
                    b.HasOne("EveLoaderEntities.DBuffCollection", null)
                        .WithMany("LocationGroupModifiers")
                        .HasForeignKey("DBuffCollectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffLocationModifier", b =>
                {
                    b.HasOne("EveLoaderEntities.DBuffCollection", null)
                        .WithMany("LocationModifiers")
                        .HasForeignKey("DBuffCollectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffLocationRequiredSkillModifier", b =>
                {
                    b.HasOne("EveLoaderEntities.DBuffCollection", null)
                        .WithMany("LocationRequiredSkillModifiers")
                        .HasForeignKey("DBuffCollectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.DogmaEffectModifierInfo", b =>
                {
                    b.HasOne("EveLoaderEntities.DogmaEffect", null)
                        .WithMany("ModifierInfo")
                        .HasForeignKey("DogmaEffectKey");
                });

            modelBuilder.Entity("EveLoaderEntities.DynamicItemAttributeRange", b =>
                {
                    b.HasOne("EveLoaderEntities.DynamicItemAttribute", null)
                        .WithMany("AttributeIDs")
                        .HasForeignKey("DynamicItemAttributeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.DynamicItemInputOutputMapping", b =>
                {
                    b.HasOne("EveLoaderEntities.DynamicItemAttribute", null)
                        .WithMany("InputOutputMapping")
                        .HasForeignKey("DynamicItemAttributeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.EpicArcMission", b =>
                {
                    b.HasOne("EveLoaderEntities.EpicArc", null)
                        .WithMany("Missions")
                        .HasForeignKey("EpicArcKey");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchemaBooleanParameter", b =>
                {
                    b.HasOne("EveLoaderEntities.FreelanceJobSchemaBooleanOption", "OptionFalse")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.FreelanceJobSchemaBooleanParameter", "OptionFalseKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EveLoaderEntities.FreelanceJobSchemaBooleanOption", "OptionTrue")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.FreelanceJobSchemaBooleanParameter", "OptionTrueKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OptionFalse");

                    b.Navigation("OptionTrue");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchemaEntry", b =>
                {
                    b.HasOne("EveLoaderEntities.FreelanceJobSchemaContributionMultiplier", "ContributionMultiplier")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.FreelanceJobSchemaEntry", "ContributionMultiplierKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EveLoaderEntities.FreelanceJobSchema", null)
                        .WithMany("Value")
                        .HasForeignKey("FreelanceJobSchemaKey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EveLoaderEntities.FreelanceJobSchemaLimit", "MaxContributionsPerParticipant")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.FreelanceJobSchemaEntry", "MaxContributionsPerParticipantKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EveLoaderEntities.FreelanceJobSchemaLimit", "MaxProgressPerContribution")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.FreelanceJobSchemaEntry", "MaxProgressPerContributionKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContributionMultiplier");

                    b.Navigation("MaxContributionsPerParticipant");

                    b.Navigation("MaxProgressPerContribution");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchemaItemDelivery", b =>
                {
                    b.HasOne("EveLoaderEntities.FreelanceJobSchemaMatcher", "DeliveryLocation")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.FreelanceJobSchemaItemDelivery", "DeliveryLocationKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeliveryLocation");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchemaParameter", b =>
                {
                    b.HasOne("EveLoaderEntities.FreelanceJobSchemaBooleanParameter", "Boolean")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.FreelanceJobSchemaParameter", "BooleanKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EveLoaderEntities.FreelanceJobSchemaEntry", null)
                        .WithMany("Parameters")
                        .HasForeignKey("FreelanceJobSchemaEntryKey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EveLoaderEntities.FreelanceJobSchemaInventoryType", "InventoryType")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.FreelanceJobSchemaParameter", "InventoryTypeKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EveLoaderEntities.FreelanceJobSchemaItemDelivery", "ItemDelivery")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.FreelanceJobSchemaParameter", "ItemDeliveryKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EveLoaderEntities.FreelanceJobSchemaMatcher", "Matcher")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.FreelanceJobSchemaParameter", "MatcherKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boolean");

                    b.Navigation("InventoryType");

                    b.Navigation("ItemDelivery");

                    b.Navigation("Matcher");
                });

            modelBuilder.Entity("EveLoaderEntities.Landmark", b =>
                {
                    b.OwnsOne("EveLoaderEntities.Position", "Position", b1 =>
                        {
                            b1.Property<long>("LandmarkKey")
                                .HasColumnType("bigint");

                            b1.Property<double>("X")
                                .HasColumnType("float")
                                .HasColumnName("PositionX");

                            b1.Property<double>("Y")
                                .HasColumnType("float")
                                .HasColumnName("PositionY");

                            b1.Property<double>("Z")
                                .HasColumnType("float")
                                .HasColumnName("PositionZ");

                            b1.HasKey("LandmarkKey");

                            b1.ToTable("Landmarks");

                            b1.WithOwner()
                                .HasForeignKey("LandmarkKey");
                        });

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("EveLoaderEntities.Blueprint", b =>
                {
                    b.Navigation("Activities")
                        .IsRequired();
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInvention", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Products");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturing", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Products");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("EveLoaderEntities.Certificate", b =>
                {
                    b.Navigation("RecommendedFor");

                    b.Navigation("SkillTypes");
                });

            modelBuilder.Entity("EveLoaderEntities.CloneGrade", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("EveLoaderEntities.ContrabandType", b =>
                {
                    b.Navigation("Factions");
                });

            modelBuilder.Entity("EveLoaderEntities.ControlTowerResource", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffCollection", b =>
                {
                    b.Navigation("ItemModifiers");

                    b.Navigation("LocationGroupModifiers");

                    b.Navigation("LocationModifiers");

                    b.Navigation("LocationRequiredSkillModifiers");
                });

            modelBuilder.Entity("EveLoaderEntities.DogmaEffect", b =>
                {
                    b.Navigation("ModifierInfo");
                });

            modelBuilder.Entity("EveLoaderEntities.DynamicItemAttribute", b =>
                {
                    b.Navigation("AttributeIDs");

                    b.Navigation("InputOutputMapping");
                });

            modelBuilder.Entity("EveLoaderEntities.EpicArc", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchema", b =>
                {
                    b.Navigation("Value");
                });

            modelBuilder.Entity("EveLoaderEntities.FreelanceJobSchemaEntry", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
