// <auto-generated />
using EveLoader.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EveLoader.Repositories.Migrations
{
    [DbContext(typeof(EveDbContext))]
    partial class EveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EveLoaderEntities.AgentType", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AgentTypes");
                });

            modelBuilder.Entity("EveLoaderEntities.AgentsInSpace", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("DungeonID")
                        .HasColumnType("bigint");

                    b.Property<long>("SolarSystemID")
                        .HasColumnType("bigint");

                    b.Property<long>("SpawnPointID")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("AgentsInSpace");
                });

            modelBuilder.Entity("EveLoaderEntities.Ancestry", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("BloodlineID")
                        .HasColumnType("bigint");

                    b.Property<long>("Charisma")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IconID")
                        .HasColumnType("bigint");

                    b.Property<long>("Intelligence")
                        .HasColumnType("bigint");

                    b.Property<long>("Memory")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Perception")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Willpower")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("Ancestries");
                });

            modelBuilder.Entity("EveLoaderEntities.Archetype", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Archetypes");
                });

            modelBuilder.Entity("EveLoaderEntities.Bloodline", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("Charisma")
                        .HasColumnType("bigint");

                    b.Property<long>("CorporationID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IconID")
                        .HasColumnType("bigint");

                    b.Property<long>("Intelligence")
                        .HasColumnType("bigint");

                    b.Property<long>("Memory")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Perception")
                        .HasColumnType("bigint");

                    b.Property<long>("RaceID")
                        .HasColumnType("bigint");

                    b.Property<long>("Willpower")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("Bloodlines");
                });

            modelBuilder.Entity("EveLoaderEntities.Blueprint", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("BlueprintTypeID")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxProductionLimit")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("Blueprints");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintActivities", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long>("BlueprintId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CopyingId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InventionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ManufacturingId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResearchMaterialId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResearchTimeId")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("BlueprintId")
                        .IsUnique();

                    b.HasIndex("CopyingId")
                        .IsUnique()
                        .HasFilter("[CopyingId] IS NOT NULL");

                    b.HasIndex("InventionId")
                        .IsUnique()
                        .HasFilter("[InventionId] IS NOT NULL");

                    b.HasIndex("ManufacturingId")
                        .IsUnique()
                        .HasFilter("[ManufacturingId] IS NOT NULL");

                    b.HasIndex("ResearchMaterialId")
                        .IsUnique()
                        .HasFilter("[ResearchMaterialId] IS NOT NULL");

                    b.HasIndex("ResearchTimeId")
                        .IsUnique()
                        .HasFilter("[ResearchTimeId] IS NOT NULL");

                    b.ToTable("BlueprintActivities");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintCopying", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("BlueprintCopying");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInvention", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("BlueprintInvention");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInventionMaterial", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("BlueprintInventionId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("BlueprintInventionId");

                    b.ToTable("BlueprintInventionMaterial");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInventionProduct", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("BlueprintInventionId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Probability")
                        .HasColumnType("float");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("BlueprintInventionId");

                    b.ToTable("BlueprintInventionProduct");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInventionSkill", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("BlueprintInventionId")
                        .HasColumnType("bigint");

                    b.Property<long>("Level")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("BlueprintInventionId");

                    b.ToTable("BlueprintInventionSkill");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturing", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("BlueprintManufacturing");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturingMaterial", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("BlueprintManufacturingKey")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("BlueprintManufacturingKey");

                    b.ToTable("BlueprintManufacturingMaterial");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturingProduct", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("BlueprintManufacturingKey")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("BlueprintManufacturingKey");

                    b.ToTable("BlueprintManufacturingProduct");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturingSkill", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("BlueprintManufacturingKey")
                        .HasColumnType("bigint");

                    b.Property<long>("Level")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("BlueprintManufacturingKey");

                    b.ToTable("BlueprintManufacturingSkill");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintResearchMaterial", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("BlueprintResearchMaterial");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintResearchTime", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("BlueprintResearchTime");
                });

            modelBuilder.Entity("EveLoaderEntities.Category", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long?>("IconID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.HasKey("Key");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EveLoaderEntities.Certificate", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("GroupID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("EveLoaderEntities.CertificateRecommendedFor", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("CertificateKey")
                        .HasColumnType("bigint");

                    b.Property<long>("RecommendedFor")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("CertificateKey");

                    b.ToTable("CertificateRecommendedFor");
                });

            modelBuilder.Entity("EveLoaderEntities.CertificateSkillType", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long>("Advanced")
                        .HasColumnType("bigint");

                    b.Property<long>("Basic")
                        .HasColumnType("bigint");

                    b.Property<long?>("CertificateKey")
                        .HasColumnType("bigint");

                    b.Property<long>("Elite")
                        .HasColumnType("bigint");

                    b.Property<long>("Improved")
                        .HasColumnType("bigint");

                    b.Property<long>("Standard")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("CertificateKey");

                    b.ToTable("CertificateSkillType");
                });

            modelBuilder.Entity("EveLoaderEntities.CharacterAttribute", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IconID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("CharacterAttributes");
                });

            modelBuilder.Entity("EveLoaderEntities.CharacterTitle", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("CharacterTitles");
                });

            modelBuilder.Entity("EveLoaderEntities.CloneGrade", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("CloneGrades");
                });

            modelBuilder.Entity("EveLoaderEntities.CloneGradeSkill", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("CloneGradeKey")
                        .HasColumnType("bigint");

                    b.Property<long>("Level")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("CloneGradeKey");

                    b.ToTable("CloneGradeSkill");
                });

            modelBuilder.Entity("EveLoaderEntities.CompressibleType", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("CompressedTypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("CompressibleTypes");
                });

            modelBuilder.Entity("EveLoaderEntities.ContrabandFaction", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<double>("AttackMinSec")
                        .HasColumnType("float");

                    b.Property<double>("ConfiscateMinSec")
                        .HasColumnType("float");

                    b.Property<long?>("ContrabandTypeKey")
                        .HasColumnType("bigint");

                    b.Property<double>("FineByValue")
                        .HasColumnType("float");

                    b.Property<double>("StandingLoss")
                        .HasColumnType("float");

                    b.HasKey("Key");

                    b.HasIndex("ContrabandTypeKey");

                    b.ToTable("ContrabandFaction");
                });

            modelBuilder.Entity("EveLoaderEntities.ContrabandType", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("ContrabandTypes");
                });

            modelBuilder.Entity("EveLoaderEntities.ControlTowerResource", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.ToTable("ControlTowerResources");
                });

            modelBuilder.Entity("EveLoaderEntities.ControlTowerResourceItem", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("ControlTowerResourceKey")
                        .HasColumnType("bigint");

                    b.Property<long?>("FactionID")
                        .HasColumnType("bigint");

                    b.Property<double?>("MinSecurityLevel")
                        .HasColumnType("float");

                    b.Property<long>("Purpose")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("ResourceTypeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("ControlTowerResourceKey");

                    b.ToTable("ControlTowerResourceItem");
                });

            modelBuilder.Entity("EveLoaderEntities.CorporationActivity", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("CorporationActivities");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffCollection", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("AggregateMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeveloperDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShowOutputValueInUI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("DBuffCollections");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffItemModifier", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("DBuffCollectionKey")
                        .HasColumnType("bigint");

                    b.Property<long>("DogmaAttributeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("DBuffCollectionKey");

                    b.ToTable("DBuffItemModifier");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffLocationGroupModifier", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("DBuffCollectionKey")
                        .HasColumnType("bigint");

                    b.Property<long>("DogmaAttributeID")
                        .HasColumnType("bigint");

                    b.Property<long>("GroupID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("DBuffCollectionKey");

                    b.ToTable("DBuffLocationGroupModifier");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffLocationModifier", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("DBuffCollectionKey")
                        .HasColumnType("bigint");

                    b.Property<long>("DogmaAttributeID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("DBuffCollectionKey");

                    b.ToTable("DBuffLocationModifier");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffLocationRequiredSkillModifier", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Key"));

                    b.Property<long?>("DBuffCollectionKey")
                        .HasColumnType("bigint");

                    b.Property<long>("DogmaAttributeID")
                        .HasColumnType("bigint");

                    b.Property<long>("SkillID")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("DBuffCollectionKey");

                    b.ToTable("DBuffLocationRequiredSkillModifier");
                });

            modelBuilder.Entity("EveLoaderEntities.DogmaAttributeCategory", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("DogmaAttributeCategories");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintActivities", b =>
                {
                    b.HasOne("EveLoaderEntities.Blueprint", null)
                        .WithOne("Activities")
                        .HasForeignKey("EveLoaderEntities.BlueprintActivities", "BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EveLoaderEntities.BlueprintCopying", "Copying")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.BlueprintActivities", "CopyingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EveLoaderEntities.BlueprintInvention", "Invention")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.BlueprintActivities", "InventionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EveLoaderEntities.BlueprintManufacturing", "Manufacturing")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.BlueprintActivities", "ManufacturingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EveLoaderEntities.BlueprintResearchMaterial", "ResearchMaterial")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.BlueprintActivities", "ResearchMaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EveLoaderEntities.BlueprintResearchTime", "ResearchTime")
                        .WithOne()
                        .HasForeignKey("EveLoaderEntities.BlueprintActivities", "ResearchTimeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Copying");

                    b.Navigation("Invention");

                    b.Navigation("Manufacturing");

                    b.Navigation("ResearchMaterial");

                    b.Navigation("ResearchTime");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInventionMaterial", b =>
                {
                    b.HasOne("EveLoaderEntities.BlueprintInvention", null)
                        .WithMany("Materials")
                        .HasForeignKey("BlueprintInventionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInventionProduct", b =>
                {
                    b.HasOne("EveLoaderEntities.BlueprintInvention", null)
                        .WithMany("Products")
                        .HasForeignKey("BlueprintInventionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInventionSkill", b =>
                {
                    b.HasOne("EveLoaderEntities.BlueprintInvention", null)
                        .WithMany("Skills")
                        .HasForeignKey("BlueprintInventionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturingMaterial", b =>
                {
                    b.HasOne("EveLoaderEntities.BlueprintManufacturing", null)
                        .WithMany("Materials")
                        .HasForeignKey("BlueprintManufacturingKey");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturingProduct", b =>
                {
                    b.HasOne("EveLoaderEntities.BlueprintManufacturing", null)
                        .WithMany("Products")
                        .HasForeignKey("BlueprintManufacturingKey");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturingSkill", b =>
                {
                    b.HasOne("EveLoaderEntities.BlueprintManufacturing", null)
                        .WithMany("Skills")
                        .HasForeignKey("BlueprintManufacturingKey");
                });

            modelBuilder.Entity("EveLoaderEntities.CertificateRecommendedFor", b =>
                {
                    b.HasOne("EveLoaderEntities.Certificate", null)
                        .WithMany("RecommendedFor")
                        .HasForeignKey("CertificateKey");
                });

            modelBuilder.Entity("EveLoaderEntities.CertificateSkillType", b =>
                {
                    b.HasOne("EveLoaderEntities.Certificate", null)
                        .WithMany("SkillTypes")
                        .HasForeignKey("CertificateKey");
                });

            modelBuilder.Entity("EveLoaderEntities.CloneGradeSkill", b =>
                {
                    b.HasOne("EveLoaderEntities.CloneGrade", null)
                        .WithMany("Skills")
                        .HasForeignKey("CloneGradeKey");
                });

            modelBuilder.Entity("EveLoaderEntities.ContrabandFaction", b =>
                {
                    b.HasOne("EveLoaderEntities.ContrabandType", null)
                        .WithMany("Factions")
                        .HasForeignKey("ContrabandTypeKey");
                });

            modelBuilder.Entity("EveLoaderEntities.ControlTowerResourceItem", b =>
                {
                    b.HasOne("EveLoaderEntities.ControlTowerResource", null)
                        .WithMany("Resources")
                        .HasForeignKey("ControlTowerResourceKey");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffItemModifier", b =>
                {
                    b.HasOne("EveLoaderEntities.DBuffCollection", null)
                        .WithMany("ItemModifiers")
                        .HasForeignKey("DBuffCollectionKey");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffLocationGroupModifier", b =>
                {
                    b.HasOne("EveLoaderEntities.DBuffCollection", null)
                        .WithMany("LocationGroupModifiers")
                        .HasForeignKey("DBuffCollectionKey");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffLocationModifier", b =>
                {
                    b.HasOne("EveLoaderEntities.DBuffCollection", null)
                        .WithMany("LocationModifiers")
                        .HasForeignKey("DBuffCollectionKey");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffLocationRequiredSkillModifier", b =>
                {
                    b.HasOne("EveLoaderEntities.DBuffCollection", null)
                        .WithMany("LocationRequiredSkillModifiers")
                        .HasForeignKey("DBuffCollectionKey");
                });

            modelBuilder.Entity("EveLoaderEntities.Blueprint", b =>
                {
                    b.Navigation("Activities")
                        .IsRequired();
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintInvention", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Products");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("EveLoaderEntities.BlueprintManufacturing", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Products");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("EveLoaderEntities.Certificate", b =>
                {
                    b.Navigation("RecommendedFor");

                    b.Navigation("SkillTypes");
                });

            modelBuilder.Entity("EveLoaderEntities.CloneGrade", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("EveLoaderEntities.ContrabandType", b =>
                {
                    b.Navigation("Factions");
                });

            modelBuilder.Entity("EveLoaderEntities.ControlTowerResource", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("EveLoaderEntities.DBuffCollection", b =>
                {
                    b.Navigation("ItemModifiers");

                    b.Navigation("LocationGroupModifiers");

                    b.Navigation("LocationModifiers");

                    b.Navigation("LocationRequiredSkillModifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
