// <auto-generated />
using EveLoader.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EveLoader.Console.Repositories.Migrations
{
    [DbContext(typeof(EveDbContext))]
    [Migration("20260910132547_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EveLoader.Console.Entities.AgentType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("Key")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("name");

                    b.HasKey("id");

                    b.ToTable("AgentTypes");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.AgentsInSpace", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("DungeonID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("dungeonID");

                    b.Property<long>("SolarSystemID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("solarSystemID");

                    b.Property<long>("SpawnPointID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("spawnPointID");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("typeID");

                    b.HasKey("Key");

                    b.ToTable("AgentsInSpace");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.Ancestry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("BloodlineID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("bloodlineID");

                    b.Property<long>("Charisma")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("charisma");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("description");

                    b.Property<long>("IconID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("iconID");

                    b.Property<long>("Intelligence")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("intelligence");

                    b.Property<long>("Key")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("_key");

                    b.Property<long>("Memory")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("memory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("name");

                    b.Property<long>("Perception")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("perception");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("shortDescription");

                    b.Property<long>("Willpower")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("willpower");

                    b.HasKey("id");

                    b.ToTable("Ancestries");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.Archetype", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("description");

                    b.Property<long>("Key")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("_key");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("title");

                    b.HasKey("id");

                    b.ToTable("Archetypes");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.Bloodline", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("Charisma")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("charisma");

                    b.Property<long>("CorporationID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("corporationID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("description");

                    b.Property<long>("IconID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("iconID");

                    b.Property<long>("Intelligence")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("intelligence");

                    b.Property<long>("Key")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("_key");

                    b.Property<long>("Memory")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("memory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("name");

                    b.Property<long>("Perception")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("perception");

                    b.Property<long>("RaceID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("raceID");

                    b.Property<long>("Willpower")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("willpower");

                    b.HasKey("id");

                    b.ToTable("Bloodlines");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.Blueprint", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<int>("Activitiesid")
                        .HasColumnType("int");

                    b.Property<long>("BlueprintTypeID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("blueprintTypeID");

                    b.Property<long>("MaxProductionLimit")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("maxProductionLimit");

                    b.HasKey("Key");

                    b.HasIndex("Activitiesid");

                    b.ToTable("Blueprints");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintActivities", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Copyingid")
                        .HasColumnType("int");

                    b.Property<int>("Inventionid")
                        .HasColumnType("int");

                    b.Property<int>("Manufacturingid")
                        .HasColumnType("int");

                    b.Property<int>("ResearchMaterialid")
                        .HasColumnType("int");

                    b.Property<int>("ResearchTimeid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Copyingid");

                    b.HasIndex("Inventionid");

                    b.HasIndex("Manufacturingid");

                    b.HasIndex("ResearchMaterialid");

                    b.HasIndex("ResearchTimeid");

                    b.ToTable("BlueprintActivities");

                    b.HasAnnotation("Relational:JsonPropertyName", "activities");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintActivity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("time");

                    b.HasKey("id");

                    b.ToTable("BlueprintActivity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BlueprintActivity");

                    b
                        .UseTphMappingStrategy()
                        .HasAnnotation("Relational:JsonPropertyName", "research_time");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintMaterial", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("BlueprintManufacturingid")
                        .HasColumnType("int");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("quantity");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("typeID");

                    b.HasKey("id");

                    b.HasIndex("BlueprintManufacturingid");

                    b.ToTable("BlueprintMaterial");

                    b.HasAnnotation("Relational:JsonPropertyName", "materials");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintProduct", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("BlueprintManufacturingid")
                        .HasColumnType("int");

                    b.Property<double?>("Probability")
                        .HasColumnType("float")
                        .HasJsonPropertyName("probability");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("quantity");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("typeID");

                    b.HasKey("id");

                    b.HasIndex("BlueprintManufacturingid");

                    b.ToTable("BlueprintProduct");

                    b.HasAnnotation("Relational:JsonPropertyName", "products");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintSkill", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("BlueprintManufacturingid")
                        .HasColumnType("int");

                    b.Property<long>("Level")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("level");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("typeID");

                    b.HasKey("id");

                    b.HasIndex("BlueprintManufacturingid");

                    b.ToTable("BlueprintSkill");

                    b.HasAnnotation("Relational:JsonPropertyName", "skills");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintManufacturing", b =>
                {
                    b.HasBaseType("EveLoader.Console.Entities.BlueprintActivity");

                    b.HasDiscriminator().HasValue("BlueprintManufacturing");

                    b.HasAnnotation("Relational:JsonPropertyName", "manufacturing");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintInvention", b =>
                {
                    b.HasBaseType("EveLoader.Console.Entities.BlueprintManufacturing");

                    b.HasDiscriminator().HasValue("BlueprintInvention");

                    b.HasAnnotation("Relational:JsonPropertyName", "invention");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.Blueprint", b =>
                {
                    b.HasOne("EveLoader.Console.Entities.BlueprintActivities", "Activities")
                        .WithMany()
                        .HasForeignKey("Activitiesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activities");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintActivities", b =>
                {
                    b.HasOne("EveLoader.Console.Entities.BlueprintActivity", "Copying")
                        .WithMany()
                        .HasForeignKey("Copyingid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EveLoader.Console.Entities.BlueprintInvention", "Invention")
                        .WithMany()
                        .HasForeignKey("Inventionid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EveLoader.Console.Entities.BlueprintManufacturing", "Manufacturing")
                        .WithMany()
                        .HasForeignKey("Manufacturingid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EveLoader.Console.Entities.BlueprintActivity", "ResearchMaterial")
                        .WithMany()
                        .HasForeignKey("ResearchMaterialid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EveLoader.Console.Entities.BlueprintActivity", "ResearchTime")
                        .WithMany()
                        .HasForeignKey("ResearchTimeid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Copying");

                    b.Navigation("Invention");

                    b.Navigation("Manufacturing");

                    b.Navigation("ResearchMaterial");

                    b.Navigation("ResearchTime");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintMaterial", b =>
                {
                    b.HasOne("EveLoader.Console.Entities.BlueprintManufacturing", null)
                        .WithMany("Materials")
                        .HasForeignKey("BlueprintManufacturingid");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintProduct", b =>
                {
                    b.HasOne("EveLoader.Console.Entities.BlueprintManufacturing", null)
                        .WithMany("Products")
                        .HasForeignKey("BlueprintManufacturingid");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintSkill", b =>
                {
                    b.HasOne("EveLoader.Console.Entities.BlueprintManufacturing", null)
                        .WithMany("Skills")
                        .HasForeignKey("BlueprintManufacturingid");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintManufacturing", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Products");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
