// <auto-generated />
using EveLoader.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EveLoader.Console.Repositories.Migrations
{
    [DbContext(typeof(EveDbContext))]
    [Migration("20260922103730_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EveLoader.Console.Entities.AgentType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("Key")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("name");

                    b.HasKey("id");

                    b.ToTable("AgentTypes");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.AgentsInSpace", b =>
                {
                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<long>("DungeonID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("dungeonID");

                    b.Property<long>("SolarSystemID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("solarSystemID");

                    b.Property<long>("SpawnPointID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("spawnPointID");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("typeID");

                    b.HasKey("Key");

                    b.ToTable("AgentsInSpace");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.Ancestry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("BloodlineID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("bloodlineID");

                    b.Property<long>("Charisma")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("charisma");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("description");

                    b.Property<long>("IconID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("iconID");

                    b.Property<long>("Intelligence")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("intelligence");

                    b.Property<long>("Key")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("_key");

                    b.Property<long>("Memory")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("memory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("name");

                    b.Property<long>("Perception")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("perception");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("shortDescription");

                    b.Property<long>("Willpower")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("willpower");

                    b.HasKey("id");

                    b.ToTable("Ancestries");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.Archetype", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("description");

                    b.Property<long>("Key")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("_key");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("title");

                    b.HasKey("id");

                    b.ToTable("Archetypes");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.Bloodline", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("Charisma")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("charisma");

                    b.Property<long>("CorporationID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("corporationID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("description");

                    b.Property<long>("IconID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("iconID");

                    b.Property<long>("Intelligence")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("intelligence");

                    b.Property<long>("Key")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("_key");

                    b.Property<long>("Memory")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("memory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("name");

                    b.Property<long>("Perception")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("perception");

                    b.Property<long>("RaceID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("raceID");

                    b.Property<long>("Willpower")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("willpower");

                    b.HasKey("id");

                    b.ToTable("Bloodlines");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.Blueprint", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("BlueprintTypeID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("blueprintTypeID");

                    b.Property<long>("MaxProductionLimit")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("maxProductionLimit");

                    b.HasKey("Id");

                    b.ToTable("Blueprints");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintActivities", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("BlueprintId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ManufacturingId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("BlueprintId")
                        .IsUnique();

                    b.HasIndex("ManufacturingId")
                        .IsUnique()
                        .HasFilter("[ManufacturingId] IS NOT NULL");

                    b.ToTable("BlueprintActivities");

                    b.HasAnnotation("Relational:JsonPropertyName", "activities");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintCopying", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ActivitiesId")
                        .HasColumnType("int");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("time");

                    b.HasKey("id");

                    b.HasIndex("ActivitiesId")
                        .IsUnique();

                    b.ToTable("BlueprintCopying");

                    b.HasAnnotation("Relational:JsonPropertyName", "copying");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintManufacturing", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("time");

                    b.HasKey("id");

                    b.ToTable("BlueprintManufacturing");

                    b.HasAnnotation("Relational:JsonPropertyName", "manufacturing");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintMaterial", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("BlueprintManufacturingid")
                        .HasColumnType("int");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("quantity");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("time");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("typeID");

                    b.HasKey("id");

                    b.HasIndex("BlueprintManufacturingid");

                    b.ToTable("BlueprintMaterial");

                    b.HasAnnotation("Relational:JsonPropertyName", "materials");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintProduct", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("BlueprintManufacturingid")
                        .HasColumnType("int");

                    b.Property<double?>("Probability")
                        .HasColumnType("float")
                        .HasJsonPropertyName("probability");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("quantity");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("typeID");

                    b.HasKey("id");

                    b.HasIndex("BlueprintManufacturingid");

                    b.ToTable("BlueprintProduct");

                    b.HasAnnotation("Relational:JsonPropertyName", "products");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintSkill", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("BlueprintManufacturingid")
                        .HasColumnType("int");

                    b.Property<long>("Level")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("level");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("typeID");

                    b.HasKey("id");

                    b.HasIndex("BlueprintManufacturingid");

                    b.ToTable("BlueprintSkill");

                    b.HasAnnotation("Relational:JsonPropertyName", "skills");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintActivities", b =>
                {
                    b.HasOne("EveLoader.Console.Entities.Blueprint", null)
                        .WithOne("Activities")
                        .HasForeignKey("EveLoader.Console.Entities.BlueprintActivities", "BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EveLoader.Console.Entities.BlueprintManufacturing", "Manufacturing")
                        .WithOne()
                        .HasForeignKey("EveLoader.Console.Entities.BlueprintActivities", "ManufacturingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manufacturing");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintCopying", b =>
                {
                    b.HasOne("EveLoader.Console.Entities.BlueprintActivities", null)
                        .WithOne("Copying")
                        .HasForeignKey("EveLoader.Console.Entities.BlueprintCopying", "ActivitiesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintMaterial", b =>
                {
                    b.HasOne("EveLoader.Console.Entities.BlueprintManufacturing", null)
                        .WithMany("Materials")
                        .HasForeignKey("BlueprintManufacturingid");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintProduct", b =>
                {
                    b.HasOne("EveLoader.Console.Entities.BlueprintManufacturing", null)
                        .WithMany("Products")
                        .HasForeignKey("BlueprintManufacturingid");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintSkill", b =>
                {
                    b.HasOne("EveLoader.Console.Entities.BlueprintManufacturing", null)
                        .WithMany("Skills")
                        .HasForeignKey("BlueprintManufacturingid");
                });

            modelBuilder.Entity("EveLoader.Console.Entities.Blueprint", b =>
                {
                    b.Navigation("Activities")
                        .IsRequired();
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintActivities", b =>
                {
                    b.Navigation("Copying")
                        .IsRequired();
                });

            modelBuilder.Entity("EveLoader.Console.Entities.BlueprintManufacturing", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Products");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
