// <auto-generated />
using EveLoader.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EveLoader.Console.Repositories.Migrations
{
    [DbContext(typeof(EveDbContext))]
    [Migration("20260903135459_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EveLoader.Entities.Db.AgentType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("Key")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("name");

                    b.HasKey("id");

                    b.ToTable("AgentTypes");
                });

            modelBuilder.Entity("EveLoader.Entities.Db.AgentsInSpace", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("DungeonID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("dungeonID");

                    b.Property<long>("Key")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("_key");

                    b.Property<long>("SolarSystemID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("solarSystemID");

                    b.Property<long>("SpawnPointID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("spawnPointID");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("typeID");

                    b.HasKey("id");

                    b.ToTable("AgentsInSpace");
                });

            modelBuilder.Entity("EveLoader.Entities.Db.Ancestry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("BloodlineID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("bloodlineID");

                    b.Property<long>("Charisma")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("charisma");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("description");

                    b.Property<long>("IconID")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("iconID");

                    b.Property<long>("Intelligence")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("intelligence");

                    b.Property<long>("Key")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("_key");

                    b.Property<long>("Memory")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("memory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("name");

                    b.Property<long>("Perception")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("perception");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("shortDescription");

                    b.Property<long>("Willpower")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("willpower");

                    b.HasKey("id");

                    b.ToTable("Ancestries");
                });

            modelBuilder.Entity("EveLoader.Entities.Db.SkinrComponentCategories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("key")
                        .HasColumnType("int")
                        .HasJsonPropertyName("_key");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SkinrComponentCategories");
                });

            modelBuilder.Entity("EveLoader.Entities.Db.SkinrSlotCategories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("key")
                        .HasColumnType("int")
                        .HasJsonPropertyName("_key");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SkinrSlotCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
